export const actionTypes = {
  CHECK_REQUESTS: 'CHECK_REQUESTS',
  CHECK_REQUEST_ERROR: 'CHECK_REQUEST_ERROR',
  SEARCH_USER: 'SEARCH_USER',
  SEARCH_USER_ERROR: 'SEARCH_USER_ERROR',
  SET_ERROR: 'SET_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
};
