export const actionTypes = {
  CHECK_REQUESTS: 'CHECK_REQUESTS',
  CHECK_REQUEST_ERROR: 'CHECK_REQUEST_ERROR',
  SEARCH_USER: 'SEARCH_USER',
  SEARCH_USER_ERROR: 'SEARCH_USER_ERROR',
  SET_ERROR: 'SET_ERROR',
  REMOVE_ERROR: 'REMOVE_ERROR',
  SET_LOADING: 'SET_LOADING',
  REMOVE_LOADING: 'REMOVE_LOADING',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  GET_FOLLOWERS_ERROR: 'GET_FOLLOWERS_ERROR',
};
